// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/schema.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 3713997970766520879),
      name: 'Invoice',
      lastPropertyId: const obx_int.IdUid(12, 6275051998814184470),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2860771734848165052),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1965726459869131648),
            name: 'userId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4162281913580287893),
            name: 'amount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 405886929286830102),
            name: 'reference',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4945279567130585821),
            name: 'invoice',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1744976370628686715),
            name: 'tableId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3373117299995068943),
            name: 'status',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 946134409511892928),
            name: 'companyId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3619177691613437743),
            name: 'lastUpdated',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 4562557524264939143),
            name: 'customerName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 6275051998814184470),
            name: 'customerPhone',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 7886241321930313604),
      name: 'Orders',
      lastPropertyId: const obx_int.IdUid(17, 5935592689397083727),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3949341919264001473),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6519141963046955154),
            name: 'customerName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7126214782565511031),
            name: 'trxId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2648942591417956233),
            name: 'productId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4659893148320221052),
            name: 'quantity',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3152506712514282775),
            name: 'amount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2888952696829683905),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8940484087225681449),
            name: 'searchDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 3373876677636134074),
            name: 'billerId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 1205116076264051373),
            name: 'paymentMethod',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 3357641646123933098),
            name: 'items',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 3741674195965367799),
            name: 'others',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 6208958557795721820),
            name: 'companyId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 5655780321355641467),
            name: 'register',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 7572106564519438970),
            name: 'status',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 3545259927243686489),
            name: 'tableId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 5935592689397083727),
            name: 'sync',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 907371886641157429),
      name: 'Register',
      lastPropertyId: const obx_int.IdUid(7, 4648692424026314471),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5792514223637512987),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6795619031527079568),
            name: 'opening',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3554332520657910164),
            name: 'closing',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5584244530362836070),
            name: 'userId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2803827132455783683),
            name: 'companyId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4972978875323159878),
            name: 'lastUpdated',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4648692424026314471),
            name: 'module',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 4870425316236824875),
      name: 'StoreX',
      lastPropertyId: const obx_int.IdUid(6, 5862790885167881528),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3809110253289751010),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3337843347607188435),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1779408574372844349),
            name: 'value',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8298604828424206970),
            name: 'billerId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1971622594885847142),
            name: 'companyId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5862790885167881528),
            name: 'lastUpdated',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 7734342654229375872),
      name: 'TableList',
      lastPropertyId: const obx_int.IdUid(5, 4780085604774968887),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6584007075911955695),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4601025079635674195),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4697447267458492846),
            name: 'userId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2980045794657061801),
            name: 'companyId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4780085604774968887),
            name: 'lastUpdated',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 9032510667798496369),
      name: 'Users',
      lastPropertyId: const obx_int.IdUid(7, 2289196681776559331),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2019763679123883014),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5370989269974339821),
            name: 'email',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2888353744974451815),
            name: 'firstName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8308759487442019248),
            name: 'lastName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8919102790096624356),
            name: 'password',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 3818400767475844457),
            name: 'companyId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2289196681776559331),
            name: 'lastUpdated',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(8, 2324787406476925088),
      name: 'BookingX',
      lastPropertyId: const obx_int.IdUid(28, 611428150378860178),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2817297939636587425),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1291695489718069333),
            name: 'uid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4480863930407698145),
            name: 'perNight',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2604714306788199092),
            name: 'checkin',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 252855649510428535),
            name: 'checkout',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2644858412525852099),
            name: 'amount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 5006428202264660327),
            name: 'roomName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2704490496937932823),
            name: 'folio',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7789725957967280134),
            name: 'amountPayable',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8000543572485749714),
            name: 'discount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 3982327013754740077),
            name: 'totalDebt',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 1459376893477414932),
            name: 'roomId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 1355944914475579022),
            name: 'folioId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 4529873495571270677),
            name: 'trx',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 4804326854573713815),
            name: 'customerId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 7971162174605182319),
            name: 'bookingOption',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 1949218177640176867),
            name: 'paymentType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 3908969225810777503),
            name: 'duration',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 3694749643872858771),
            name: 'status',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(20, 8268244657851584826),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(21, 7672391129609983624),
            name: 'others',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(22, 3105975879762692264),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(23, 5878433308935765190),
            name: 'userId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(24, 2617809280932046313),
            name: 'cancelReason',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(25, 7915689669724858805),
            name: 'checkoutTime',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(26, 8107794296391688972),
            name: 'checkinTime',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(27, 1561063325542444590),
            name: 'companyId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(28, 611428150378860178),
            name: 'searchDate',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(9, 2180851869646946073),
      name: 'FolioX',
      lastPropertyId: const obx_int.IdUid(19, 2150309264690142391),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5473547737117919780),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5850453374325823268),
            name: 'uid',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6521137934994473090),
            name: 'customerName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4642845487238042130),
            name: 'customerAddress',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8586109486163530594),
            name: 'customerPhone',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2168427639109290455),
            name: 'arrivalDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7605577010840163771),
            name: 'departureDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6583768237771550699),
            name: 'balance',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 951258858943914977),
            name: 'debit',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8018592150805429778),
            name: 'credit',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 5090322898969061845),
            name: 'type',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 6107604636302357586),
            name: 'discount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 6926227199426526519),
            name: 'trackID',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 4410200426358346938),
            name: 'status',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 2860088052188191763),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 4219514169337809227),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 3652510186633155072),
            name: 'userId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 1735516794890717198),
            name: 'companyId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(19, 2150309264690142391),
            name: 'searchDate',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(9, 2180851869646946073),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [3453426442867826984],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        2236340060700229950,
        1687928428401695919,
        6529130396651546832,
        6096795919361313911,
        6659375149775568942,
        3438337723090293099,
        1457918232246583737,
        3936246207180397150,
        8292076467639872806,
        6572584623227258166,
        2355834836995474316,
        5462926671953039939,
        2901679270864098273,
        7052074975117597015,
        8546391678938953982,
        697382656730597704,
        7358144032051179023,
        204610702334447992,
        728470876276562073,
        5683672372679719884,
        5683298522401146766,
        8694009957010433427,
        636419951267534941,
        8611989815849235057,
        767830926285875043,
        5912845798230417177,
        6649215881229165045,
        4633140566523539235,
        5945536197580053257
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Invoice: obx_int.EntityDefinition<Invoice>(
        model: _entities[0],
        toOneRelations: (Invoice object) => [],
        toManyRelations: (Invoice object) => {},
        getId: (Invoice object) => object.id,
        setId: (Invoice object, int id) {
          object.id = id;
        },
        objectToFB: (Invoice object, fb.Builder fbb) {
          final userIdOffset = fbb.writeString(object.userId);
          final referenceOffset = fbb.writeString(object.reference);
          final invoiceOffset = fbb.writeString(object.invoice);
          final tableIdOffset =
              object.tableId == null ? null : fbb.writeString(object.tableId!);
          final statusOffset = fbb.writeString(object.status);
          final companyIdOffset = fbb.writeString(object.companyId);
          final lastUpdatedOffset = fbb.writeString(object.lastUpdated);
          final customerNameOffset = fbb.writeString(object.customerName);
          final customerPhoneOffset = fbb.writeString(object.customerPhone);
          fbb.startTable(13);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, userIdOffset);
          fbb.addFloat64(2, object.amount);
          fbb.addOffset(3, referenceOffset);
          fbb.addOffset(4, invoiceOffset);
          fbb.addOffset(5, tableIdOffset);
          fbb.addOffset(6, statusOffset);
          fbb.addOffset(7, companyIdOffset);
          fbb.addOffset(8, lastUpdatedOffset);
          fbb.addOffset(10, customerNameOffset);
          fbb.addOffset(11, customerPhoneOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final userIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final amountParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final referenceParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final invoiceParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final statusParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final companyIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final lastUpdatedParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 20, '');
          final tableIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final customerNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 24, '');
          final customerPhoneParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 26, '');
          final object = Invoice(
              userId: userIdParam,
              amount: amountParam,
              reference: referenceParam,
              invoice: invoiceParam,
              status: statusParam,
              companyId: companyIdParam,
              lastUpdated: lastUpdatedParam,
              tableId: tableIdParam,
              customerName: customerNameParam,
              customerPhone: customerPhoneParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    Orders: obx_int.EntityDefinition<Orders>(
        model: _entities[1],
        toOneRelations: (Orders object) => [],
        toManyRelations: (Orders object) => {},
        getId: (Orders object) => object.id,
        setId: (Orders object, int id) {
          object.id = id;
        },
        objectToFB: (Orders object, fb.Builder fbb) {
          final customerNameOffset = fbb.writeString(object.customerName);
          final trxIdOffset = fbb.writeString(object.trxId);
          final searchDateOffset = fbb.writeString(object.searchDate);
          final paymentMethodOffset = fbb.writeString(object.paymentMethod);
          final itemsOffset = fbb.writeString(object.items);
          final othersOffset = fbb.writeString(object.others);
          final companyIdOffset = fbb.writeString(object.companyId);
          final registerOffset = fbb.writeString(object.register);
          final tableIdOffset =
              object.tableId == null ? null : fbb.writeString(object.tableId!);
          fbb.startTable(18);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, customerNameOffset);
          fbb.addOffset(2, trxIdOffset);
          fbb.addInt64(3, object.productId);
          fbb.addInt64(4, object.quantity);
          fbb.addFloat64(5, object.amount);
          fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
          fbb.addOffset(7, searchDateOffset);
          fbb.addInt64(8, object.billerId);
          fbb.addOffset(9, paymentMethodOffset);
          fbb.addOffset(10, itemsOffset);
          fbb.addOffset(11, othersOffset);
          fbb.addOffset(12, companyIdOffset);
          fbb.addOffset(13, registerOffset);
          fbb.addInt64(14, object.status);
          fbb.addOffset(15, tableIdOffset);
          fbb.addInt64(16, object.sync);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final customerNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, '');
          final trxIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final productIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final quantityParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final amountParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          final searchDateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final billerIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final paymentMethodParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 22, '');
          final itemsParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 24, '');
          final othersParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 26, '');
          final companyIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 28, '');
          final registerParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 30, '');
          final statusParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0);
          final tableIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 34);
          final syncParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 36, 0);
          final object = Orders(
              customerName: customerNameParam,
              trxId: trxIdParam,
              productId: productIdParam,
              quantity: quantityParam,
              amount: amountParam,
              createdAt: createdAtParam,
              searchDate: searchDateParam,
              billerId: billerIdParam,
              paymentMethod: paymentMethodParam,
              items: itemsParam,
              others: othersParam,
              companyId: companyIdParam,
              register: registerParam,
              status: statusParam,
              tableId: tableIdParam,
              sync: syncParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    Register: obx_int.EntityDefinition<Register>(
        model: _entities[2],
        toOneRelations: (Register object) => [],
        toManyRelations: (Register object) => {},
        getId: (Register object) => object.id,
        setId: (Register object, int id) {
          object.id = id;
        },
        objectToFB: (Register object, fb.Builder fbb) {
          final openingOffset = fbb.writeString(object.opening);
          final closingOffset = fbb.writeString(object.closing);
          final userIdOffset = fbb.writeString(object.userId);
          final companyIdOffset = fbb.writeString(object.companyId);
          final lastUpdatedOffset = fbb.writeString(object.lastUpdated);
          final moduleOffset = fbb.writeString(object.module);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, openingOffset);
          fbb.addOffset(2, closingOffset);
          fbb.addOffset(3, userIdOffset);
          fbb.addOffset(4, companyIdOffset);
          fbb.addOffset(5, lastUpdatedOffset);
          fbb.addOffset(6, moduleOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final openingParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final closingParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final userIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final moduleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final companyIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final lastUpdatedParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final object = Register(
              opening: openingParam,
              closing: closingParam,
              userId: userIdParam,
              module: moduleParam,
              companyId: companyIdParam,
              lastUpdated: lastUpdatedParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    StoreX: obx_int.EntityDefinition<StoreX>(
        model: _entities[3],
        toOneRelations: (StoreX object) => [],
        toManyRelations: (StoreX object) => {},
        getId: (StoreX object) => object.id,
        setId: (StoreX object, int id) {
          object.id = id;
        },
        objectToFB: (StoreX object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final valueOffset = fbb.writeString(object.value);
          final billerIdOffset = fbb.writeString(object.billerId);
          final companyIdOffset = fbb.writeString(object.companyId);
          final lastUpdatedOffset = fbb.writeString(object.lastUpdated);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, valueOffset);
          fbb.addOffset(3, billerIdOffset);
          fbb.addOffset(4, companyIdOffset);
          fbb.addOffset(5, lastUpdatedOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final valueParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final billerIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final companyIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final lastUpdatedParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final object = StoreX(
              name: nameParam,
              value: valueParam,
              billerId: billerIdParam,
              companyId: companyIdParam,
              lastUpdated: lastUpdatedParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    TableList: obx_int.EntityDefinition<TableList>(
        model: _entities[4],
        toOneRelations: (TableList object) => [],
        toManyRelations: (TableList object) => {},
        getId: (TableList object) => object.id,
        setId: (TableList object, int id) {
          object.id = id;
        },
        objectToFB: (TableList object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final userIdOffset = fbb.writeString(object.userId);
          final companyIdOffset = fbb.writeString(object.companyId);
          final lastUpdatedOffset = fbb.writeString(object.lastUpdated);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, userIdOffset);
          fbb.addOffset(3, companyIdOffset);
          fbb.addOffset(4, lastUpdatedOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final userIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final companyIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final lastUpdatedParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final object = TableList(
              name: nameParam,
              userId: userIdParam,
              companyId: companyIdParam,
              lastUpdated: lastUpdatedParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    Users: obx_int.EntityDefinition<Users>(
        model: _entities[5],
        toOneRelations: (Users object) => [],
        toManyRelations: (Users object) => {},
        getId: (Users object) => object.id,
        setId: (Users object, int id) {
          object.id = id;
        },
        objectToFB: (Users object, fb.Builder fbb) {
          final emailOffset = fbb.writeString(object.email);
          final firstNameOffset = fbb.writeString(object.firstName);
          final lastNameOffset = fbb.writeString(object.lastName);
          final passwordOffset = fbb.writeString(object.password);
          final companyIdOffset = fbb.writeString(object.companyId);
          final lastUpdatedOffset = fbb.writeString(object.lastUpdated);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, emailOffset);
          fbb.addOffset(2, firstNameOffset);
          fbb.addOffset(3, lastNameOffset);
          fbb.addOffset(4, passwordOffset);
          fbb.addOffset(5, companyIdOffset);
          fbb.addOffset(6, lastUpdatedOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final emailParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final firstNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final lastNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final passwordParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final companyIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final lastUpdatedParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, '');
          final object = Users(
              email: emailParam,
              firstName: firstNameParam,
              lastName: lastNameParam,
              password: passwordParam,
              companyId: companyIdParam,
              lastUpdated: lastUpdatedParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    BookingX: obx_int.EntityDefinition<BookingX>(
        model: _entities[6],
        toOneRelations: (BookingX object) => [],
        toManyRelations: (BookingX object) => {},
        getId: (BookingX object) => object.id,
        setId: (BookingX object, int id) {
          object.id = id;
        },
        objectToFB: (BookingX object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final perNightOffset = fbb.writeString(object.perNight);
          final checkinOffset = fbb.writeString(object.checkin);
          final checkoutOffset = fbb.writeString(object.checkout);
          final roomNameOffset = fbb.writeString(object.roomName);
          final folioOffset = fbb.writeString(object.folio);
          final roomIdOffset = fbb.writeString(object.roomId);
          final trxOffset = fbb.writeString(object.trx);
          final customerIdOffset = object.customerId == null
              ? null
              : fbb.writeString(object.customerId!);
          final bookingOptionOffset = fbb.writeString(object.bookingOption);
          final paymentTypeOffset = object.paymentType == null
              ? null
              : fbb.writeString(object.paymentType!);
          final durationOffset = fbb.writeString(object.duration);
          final othersOffset = fbb.writeString(object.others);
          final userIdOffset = fbb.writeString(object.userId);
          final cancelReasonOffset = object.cancelReason == null
              ? null
              : fbb.writeString(object.cancelReason!);
          final checkoutTimeOffset = object.checkoutTime == null
              ? null
              : fbb.writeString(object.checkoutTime!);
          final checkinTimeOffset = object.checkinTime == null
              ? null
              : fbb.writeString(object.checkinTime!);
          final companyIdOffset = object.companyId == null
              ? null
              : fbb.writeString(object.companyId!);
          final searchDateOffset = object.searchDate == null
              ? null
              : fbb.writeString(object.searchDate!);
          fbb.startTable(29);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, perNightOffset);
          fbb.addOffset(3, checkinOffset);
          fbb.addOffset(4, checkoutOffset);
          fbb.addFloat64(5, object.amount);
          fbb.addOffset(6, roomNameOffset);
          fbb.addOffset(7, folioOffset);
          fbb.addFloat64(8, object.amountPayable);
          fbb.addInt64(9, object.discount);
          fbb.addFloat64(10, object.totalDebt);
          fbb.addOffset(11, roomIdOffset);
          fbb.addInt64(12, object.folioId);
          fbb.addOffset(13, trxOffset);
          fbb.addOffset(14, customerIdOffset);
          fbb.addOffset(15, bookingOptionOffset);
          fbb.addOffset(16, paymentTypeOffset);
          fbb.addOffset(17, durationOffset);
          fbb.addBool(18, object.status);
          fbb.addInt64(19, object.createdAt?.millisecondsSinceEpoch);
          fbb.addOffset(20, othersOffset);
          fbb.addInt64(21, object.updatedAt?.millisecondsSinceEpoch);
          fbb.addOffset(22, userIdOffset);
          fbb.addOffset(23, cancelReasonOffset);
          fbb.addOffset(24, checkoutTimeOffset);
          fbb.addOffset(25, checkinTimeOffset);
          fbb.addOffset(26, companyIdOffset);
          fbb.addOffset(27, searchDateOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 42);
          final updatedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 46);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final perNightParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final checkinParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final checkoutParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final amountParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final roomNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final folioParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final amountPayableParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 20);
          final discountParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 22);
          final totalDebtParam = const fb.Float64Reader()
              .vTableGetNullable(buffer, rootOffset, 24);
          final roomIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 26, '');
          final folioIdParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 28);
          final trxParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 30, '');
          final customerIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 32);
          final bookingOptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 34, '');
          final paymentTypeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 36);
          final durationParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 38, '');
          final othersParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 44, '');
          final statusParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 40, false);
          final createdAtParam = createdAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
          final updatedAtParam = updatedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
          final userIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 48, '');
          final cancelReasonParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 50);
          final checkoutTimeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 52);
          final checkinTimeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 54);
          final companyIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 56);
          final searchDateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 58);
          final object = BookingX(
              id: idParam,
              uid: uidParam,
              perNight: perNightParam,
              checkin: checkinParam,
              checkout: checkoutParam,
              amount: amountParam,
              roomName: roomNameParam,
              folio: folioParam,
              amountPayable: amountPayableParam,
              discount: discountParam,
              totalDebt: totalDebtParam,
              roomId: roomIdParam,
              folioId: folioIdParam,
              trx: trxParam,
              customerId: customerIdParam,
              bookingOption: bookingOptionParam,
              paymentType: paymentTypeParam,
              duration: durationParam,
              others: othersParam,
              status: statusParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam,
              userId: userIdParam,
              cancelReason: cancelReasonParam,
              checkoutTime: checkoutTimeParam,
              checkinTime: checkinTimeParam,
              companyId: companyIdParam,
              searchDate: searchDateParam);

          return object;
        }),
    FolioX: obx_int.EntityDefinition<FolioX>(
        model: _entities[7],
        toOneRelations: (FolioX object) => [],
        toManyRelations: (FolioX object) => {},
        getId: (FolioX object) => object.id,
        setId: (FolioX object, int id) {
          object.id = id;
        },
        objectToFB: (FolioX object, fb.Builder fbb) {
          final uidOffset = fbb.writeString(object.uid);
          final customerNameOffset = fbb.writeString(object.customerName);
          final customerAddressOffset = fbb.writeString(object.customerAddress);
          final customerPhoneOffset = fbb.writeString(object.customerPhone);
          final arrivalDateOffset = fbb.writeString(object.arrivalDate);
          final departureDateOffset = fbb.writeString(object.departureDate);
          final typeOffset = fbb.writeString(object.type);
          final trackIDOffset = fbb.writeString(object.trackID);
          final userIdOffset = fbb.writeString(object.userId);
          final companyIdOffset = object.companyId == null
              ? null
              : fbb.writeString(object.companyId!);
          final searchDateOffset = object.searchDate == null
              ? null
              : fbb.writeString(object.searchDate!);
          fbb.startTable(20);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uidOffset);
          fbb.addOffset(2, customerNameOffset);
          fbb.addOffset(3, customerAddressOffset);
          fbb.addOffset(4, customerPhoneOffset);
          fbb.addOffset(5, arrivalDateOffset);
          fbb.addOffset(6, departureDateOffset);
          fbb.addFloat64(7, object.balance);
          fbb.addFloat64(8, object.debit);
          fbb.addFloat64(9, object.credit);
          fbb.addOffset(10, typeOffset);
          fbb.addInt64(11, object.discount);
          fbb.addOffset(12, trackIDOffset);
          fbb.addBool(13, object.status);
          fbb.addInt64(14, object.createdAt?.millisecondsSinceEpoch);
          fbb.addInt64(15, object.updatedAt?.millisecondsSinceEpoch);
          fbb.addOffset(16, userIdOffset);
          fbb.addOffset(17, companyIdOffset);
          fbb.addOffset(18, searchDateOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 32);
          final updatedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 34);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final uidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final customerNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final customerAddressParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final customerPhoneParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final arrivalDateParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final departureDateParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, '');
          final balanceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final creditParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final debitParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 24, '');
          final discountParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 26);
          final trackIDParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 28, '');
          final statusParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 30, false);
          final createdAtParam = createdAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
          final updatedAtParam = updatedAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
          final userIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 36, '');
          final companyIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 38);
          final searchDateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 40);
          final object = FolioX(
              id: idParam,
              uid: uidParam,
              customerName: customerNameParam,
              customerAddress: customerAddressParam,
              customerPhone: customerPhoneParam,
              arrivalDate: arrivalDateParam,
              departureDate: departureDateParam,
              balance: balanceParam,
              credit: creditParam,
              debit: debitParam,
              type: typeParam,
              discount: discountParam,
              trackID: trackIDParam,
              status: statusParam,
              createdAt: createdAtParam,
              updatedAt: updatedAtParam,
              userId: userIdParam,
              companyId: companyIdParam,
              searchDate: searchDateParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Invoice] entity fields to define ObjectBox queries.
class Invoice_ {
  /// See [Invoice.id].
  static final id =
      obx.QueryIntegerProperty<Invoice>(_entities[0].properties[0]);

  /// See [Invoice.userId].
  static final userId =
      obx.QueryStringProperty<Invoice>(_entities[0].properties[1]);

  /// See [Invoice.amount].
  static final amount =
      obx.QueryDoubleProperty<Invoice>(_entities[0].properties[2]);

  /// See [Invoice.reference].
  static final reference =
      obx.QueryStringProperty<Invoice>(_entities[0].properties[3]);

  /// See [Invoice.invoice].
  static final invoice =
      obx.QueryStringProperty<Invoice>(_entities[0].properties[4]);

  /// See [Invoice.tableId].
  static final tableId =
      obx.QueryStringProperty<Invoice>(_entities[0].properties[5]);

  /// See [Invoice.status].
  static final status =
      obx.QueryStringProperty<Invoice>(_entities[0].properties[6]);

  /// See [Invoice.companyId].
  static final companyId =
      obx.QueryStringProperty<Invoice>(_entities[0].properties[7]);

  /// See [Invoice.lastUpdated].
  static final lastUpdated =
      obx.QueryStringProperty<Invoice>(_entities[0].properties[8]);

  /// See [Invoice.customerName].
  static final customerName =
      obx.QueryStringProperty<Invoice>(_entities[0].properties[9]);

  /// See [Invoice.customerPhone].
  static final customerPhone =
      obx.QueryStringProperty<Invoice>(_entities[0].properties[10]);
}

/// [Orders] entity fields to define ObjectBox queries.
class Orders_ {
  /// See [Orders.id].
  static final id =
      obx.QueryIntegerProperty<Orders>(_entities[1].properties[0]);

  /// See [Orders.customerName].
  static final customerName =
      obx.QueryStringProperty<Orders>(_entities[1].properties[1]);

  /// See [Orders.trxId].
  static final trxId =
      obx.QueryStringProperty<Orders>(_entities[1].properties[2]);

  /// See [Orders.productId].
  static final productId =
      obx.QueryIntegerProperty<Orders>(_entities[1].properties[3]);

  /// See [Orders.quantity].
  static final quantity =
      obx.QueryIntegerProperty<Orders>(_entities[1].properties[4]);

  /// See [Orders.amount].
  static final amount =
      obx.QueryDoubleProperty<Orders>(_entities[1].properties[5]);

  /// See [Orders.createdAt].
  static final createdAt =
      obx.QueryDateProperty<Orders>(_entities[1].properties[6]);

  /// See [Orders.searchDate].
  static final searchDate =
      obx.QueryStringProperty<Orders>(_entities[1].properties[7]);

  /// See [Orders.billerId].
  static final billerId =
      obx.QueryIntegerProperty<Orders>(_entities[1].properties[8]);

  /// See [Orders.paymentMethod].
  static final paymentMethod =
      obx.QueryStringProperty<Orders>(_entities[1].properties[9]);

  /// See [Orders.items].
  static final items =
      obx.QueryStringProperty<Orders>(_entities[1].properties[10]);

  /// See [Orders.others].
  static final others =
      obx.QueryStringProperty<Orders>(_entities[1].properties[11]);

  /// See [Orders.companyId].
  static final companyId =
      obx.QueryStringProperty<Orders>(_entities[1].properties[12]);

  /// See [Orders.register].
  static final register =
      obx.QueryStringProperty<Orders>(_entities[1].properties[13]);

  /// See [Orders.status].
  static final status =
      obx.QueryIntegerProperty<Orders>(_entities[1].properties[14]);

  /// See [Orders.tableId].
  static final tableId =
      obx.QueryStringProperty<Orders>(_entities[1].properties[15]);

  /// See [Orders.sync].
  static final sync =
      obx.QueryIntegerProperty<Orders>(_entities[1].properties[16]);
}

/// [Register] entity fields to define ObjectBox queries.
class Register_ {
  /// See [Register.id].
  static final id =
      obx.QueryIntegerProperty<Register>(_entities[2].properties[0]);

  /// See [Register.opening].
  static final opening =
      obx.QueryStringProperty<Register>(_entities[2].properties[1]);

  /// See [Register.closing].
  static final closing =
      obx.QueryStringProperty<Register>(_entities[2].properties[2]);

  /// See [Register.userId].
  static final userId =
      obx.QueryStringProperty<Register>(_entities[2].properties[3]);

  /// See [Register.companyId].
  static final companyId =
      obx.QueryStringProperty<Register>(_entities[2].properties[4]);

  /// See [Register.lastUpdated].
  static final lastUpdated =
      obx.QueryStringProperty<Register>(_entities[2].properties[5]);

  /// See [Register.module].
  static final module =
      obx.QueryStringProperty<Register>(_entities[2].properties[6]);
}

/// [StoreX] entity fields to define ObjectBox queries.
class StoreX_ {
  /// See [StoreX.id].
  static final id =
      obx.QueryIntegerProperty<StoreX>(_entities[3].properties[0]);

  /// See [StoreX.name].
  static final name =
      obx.QueryStringProperty<StoreX>(_entities[3].properties[1]);

  /// See [StoreX.value].
  static final value =
      obx.QueryStringProperty<StoreX>(_entities[3].properties[2]);

  /// See [StoreX.billerId].
  static final billerId =
      obx.QueryStringProperty<StoreX>(_entities[3].properties[3]);

  /// See [StoreX.companyId].
  static final companyId =
      obx.QueryStringProperty<StoreX>(_entities[3].properties[4]);

  /// See [StoreX.lastUpdated].
  static final lastUpdated =
      obx.QueryStringProperty<StoreX>(_entities[3].properties[5]);
}

/// [TableList] entity fields to define ObjectBox queries.
class TableList_ {
  /// See [TableList.id].
  static final id =
      obx.QueryIntegerProperty<TableList>(_entities[4].properties[0]);

  /// See [TableList.name].
  static final name =
      obx.QueryStringProperty<TableList>(_entities[4].properties[1]);

  /// See [TableList.userId].
  static final userId =
      obx.QueryStringProperty<TableList>(_entities[4].properties[2]);

  /// See [TableList.companyId].
  static final companyId =
      obx.QueryStringProperty<TableList>(_entities[4].properties[3]);

  /// See [TableList.lastUpdated].
  static final lastUpdated =
      obx.QueryStringProperty<TableList>(_entities[4].properties[4]);
}

/// [Users] entity fields to define ObjectBox queries.
class Users_ {
  /// See [Users.id].
  static final id = obx.QueryIntegerProperty<Users>(_entities[5].properties[0]);

  /// See [Users.email].
  static final email =
      obx.QueryStringProperty<Users>(_entities[5].properties[1]);

  /// See [Users.firstName].
  static final firstName =
      obx.QueryStringProperty<Users>(_entities[5].properties[2]);

  /// See [Users.lastName].
  static final lastName =
      obx.QueryStringProperty<Users>(_entities[5].properties[3]);

  /// See [Users.password].
  static final password =
      obx.QueryStringProperty<Users>(_entities[5].properties[4]);

  /// See [Users.companyId].
  static final companyId =
      obx.QueryStringProperty<Users>(_entities[5].properties[5]);

  /// See [Users.lastUpdated].
  static final lastUpdated =
      obx.QueryStringProperty<Users>(_entities[5].properties[6]);
}

/// [BookingX] entity fields to define ObjectBox queries.
class BookingX_ {
  /// See [BookingX.id].
  static final id =
      obx.QueryIntegerProperty<BookingX>(_entities[6].properties[0]);

  /// See [BookingX.uid].
  static final uid =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[1]);

  /// See [BookingX.perNight].
  static final perNight =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[2]);

  /// See [BookingX.checkin].
  static final checkin =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[3]);

  /// See [BookingX.checkout].
  static final checkout =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[4]);

  /// See [BookingX.amount].
  static final amount =
      obx.QueryDoubleProperty<BookingX>(_entities[6].properties[5]);

  /// See [BookingX.roomName].
  static final roomName =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[6]);

  /// See [BookingX.folio].
  static final folio =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[7]);

  /// See [BookingX.amountPayable].
  static final amountPayable =
      obx.QueryDoubleProperty<BookingX>(_entities[6].properties[8]);

  /// See [BookingX.discount].
  static final discount =
      obx.QueryIntegerProperty<BookingX>(_entities[6].properties[9]);

  /// See [BookingX.totalDebt].
  static final totalDebt =
      obx.QueryDoubleProperty<BookingX>(_entities[6].properties[10]);

  /// See [BookingX.roomId].
  static final roomId =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[11]);

  /// See [BookingX.folioId].
  static final folioId =
      obx.QueryIntegerProperty<BookingX>(_entities[6].properties[12]);

  /// See [BookingX.trx].
  static final trx =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[13]);

  /// See [BookingX.customerId].
  static final customerId =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[14]);

  /// See [BookingX.bookingOption].
  static final bookingOption =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[15]);

  /// See [BookingX.paymentType].
  static final paymentType =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[16]);

  /// See [BookingX.duration].
  static final duration =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[17]);

  /// See [BookingX.status].
  static final status =
      obx.QueryBooleanProperty<BookingX>(_entities[6].properties[18]);

  /// See [BookingX.createdAt].
  static final createdAt =
      obx.QueryDateProperty<BookingX>(_entities[6].properties[19]);

  /// See [BookingX.others].
  static final others =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[20]);

  /// See [BookingX.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<BookingX>(_entities[6].properties[21]);

  /// See [BookingX.userId].
  static final userId =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[22]);

  /// See [BookingX.cancelReason].
  static final cancelReason =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[23]);

  /// See [BookingX.checkoutTime].
  static final checkoutTime =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[24]);

  /// See [BookingX.checkinTime].
  static final checkinTime =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[25]);

  /// See [BookingX.companyId].
  static final companyId =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[26]);

  /// See [BookingX.searchDate].
  static final searchDate =
      obx.QueryStringProperty<BookingX>(_entities[6].properties[27]);
}

/// [FolioX] entity fields to define ObjectBox queries.
class FolioX_ {
  /// See [FolioX.id].
  static final id =
      obx.QueryIntegerProperty<FolioX>(_entities[7].properties[0]);

  /// See [FolioX.uid].
  static final uid =
      obx.QueryStringProperty<FolioX>(_entities[7].properties[1]);

  /// See [FolioX.customerName].
  static final customerName =
      obx.QueryStringProperty<FolioX>(_entities[7].properties[2]);

  /// See [FolioX.customerAddress].
  static final customerAddress =
      obx.QueryStringProperty<FolioX>(_entities[7].properties[3]);

  /// See [FolioX.customerPhone].
  static final customerPhone =
      obx.QueryStringProperty<FolioX>(_entities[7].properties[4]);

  /// See [FolioX.arrivalDate].
  static final arrivalDate =
      obx.QueryStringProperty<FolioX>(_entities[7].properties[5]);

  /// See [FolioX.departureDate].
  static final departureDate =
      obx.QueryStringProperty<FolioX>(_entities[7].properties[6]);

  /// See [FolioX.balance].
  static final balance =
      obx.QueryDoubleProperty<FolioX>(_entities[7].properties[7]);

  /// See [FolioX.debit].
  static final debit =
      obx.QueryDoubleProperty<FolioX>(_entities[7].properties[8]);

  /// See [FolioX.credit].
  static final credit =
      obx.QueryDoubleProperty<FolioX>(_entities[7].properties[9]);

  /// See [FolioX.type].
  static final type =
      obx.QueryStringProperty<FolioX>(_entities[7].properties[10]);

  /// See [FolioX.discount].
  static final discount =
      obx.QueryIntegerProperty<FolioX>(_entities[7].properties[11]);

  /// See [FolioX.trackID].
  static final trackID =
      obx.QueryStringProperty<FolioX>(_entities[7].properties[12]);

  /// See [FolioX.status].
  static final status =
      obx.QueryBooleanProperty<FolioX>(_entities[7].properties[13]);

  /// See [FolioX.createdAt].
  static final createdAt =
      obx.QueryDateProperty<FolioX>(_entities[7].properties[14]);

  /// See [FolioX.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<FolioX>(_entities[7].properties[15]);

  /// See [FolioX.userId].
  static final userId =
      obx.QueryStringProperty<FolioX>(_entities[7].properties[16]);

  /// See [FolioX.companyId].
  static final companyId =
      obx.QueryStringProperty<FolioX>(_entities[7].properties[17]);

  /// See [FolioX.searchDate].
  static final searchDate =
      obx.QueryStringProperty<FolioX>(_entities[7].properties[18]);
}
